set ts=4
set sw=4
set incsearch
set ruler
set expandtab
set autoindent
set visualbell
set numberwidth=1
autocmd FileType ruby setl sw=2 sts=2 et
autocmd FileType ruby setl sw=2 sts=2 et
colorscheme desert
syntax enable
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE
